### ISSUE TITLE
Crash after opening on Gentoo

### ISSUE THREAD

**Issue by khaosgrille** [bleakgrey/tootle#142] opened 2019-04-23 21:22 UTC
Hi,
after I signed in the first time the main window opens and crashed immediatly. I tried to open it again and got the following error: 

[INFO 23:13:38.559921] Application.vala:154: Tootle version: 0.2.0
[INFO 23:13:38.559983] Application.vala:156: Kernel version: 4.19.12
[INFO 23:13:38.618897] Notificator.vala:40: Starting: /api/v1/streaming/?stre
[INFO 23:13:38.622315] Notificator.vala:40: Starting: /api/v1/streaming/?stre
[INFO 23:13:38.626113] Notificator.vala:40: Starting: /api/v1/streaming/?stre
[INFO 23:13:38.627572] Notificator.vala:40: Starting: /api/v1/streaming/?stre

(tootle:27557): Gtk-WARNING **: 23:13:38.696: gtk_window_set_titlebar() calle
[INFO 23:13:39.417526] Watchlist.vala:23: Reloading
[INFO 23:13:39.417783] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/var/tmp/portage/net-misc/tootle-0.2.0/work/tootle-0.2.0/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
[1]    27557 abort      tootle

**Comment by sphinxc0re** [comment] 2019-04-24 12:10
I have the exact same problem on NixOS

**Comment by bleakgrey** [comment] 2019-04-24 18:52
Dupe of #140

**Closed by bleakgrey** 2019-04-24 18:52 UTC
