### ISSUE TITLE
Tootle crashes on startup

### ISSUE THREAD

**Issue by agraven** [bleakgrey/tootle#151] opened 2019-06-11 16:44 UTC
When I open tootle, the startup screen shows up for a few seconds without loading any toots, and then crashes. This started happening today across all my devices.

I'm using 0.2.0-2 on Ubuntu 19.04

The terminal output is:
```
[INFO 18:43:57.796426] Application.vala:155: Tootle version: 0.2.0
[INFO 18:43:57.796453] Application.vala:157: Kernel version: 5.0.0-15-generic
[INFO 18:43:57.813648] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 18:43:57.815470] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 18:43:57.818255] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 18:43:57.819378] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(tootle:23216): Gtk-WARNING **: 18:43:57.896: gtk_window_set_titlebar() called on a realized window
[INFO 18:43:58.237423] Watchlist.vala:23: Reloading
[INFO 18:43:58.237601] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
```

**Comment by bleakgrey** [comment] 2019-06-11 20:42
Dupe of #140

**Closed by bleakgrey** 2019-06-11 20:42 UTC
