### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by sgtnasty** [bleakgrey/tootle#292] opened 2021-03-03 23:02 UTC
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
After successfully logging in to mastodon, it should not crash when loading initial content for user. 

#### What happened instead:
Application crashes with core dump.

#### How to reproduce:
1. Log into a mastodon.social account
2. Launch the application

#### Screenshots (if applicable):
__

#### Build context:
 - **Distro:** Ubuntu 20.10
 - **App version:** 0+git.0322703
 - **Build type:** snap

#### Logs:
````(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.673: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.676: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.676: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name
[INFO 17:54:16.724660] Application.vala:156: Tootle version: 0.2.0
[INFO 17:54:16.724689] Application.vala:158: Kernel version: 5.8.0-44-generic
[INFO 17:54:16.758646] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 17:54:16.760546] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 17:54:16.764236] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 17:54:16.765341] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.769: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.772: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.773: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name

(com.github.bleakgrey.tootle:36399): Gtk-WARNING **: 17:54:16.964: gtk_window_set_titlebar() called on a realized window
[INFO 17:54:18.024385] Watchlist.vala:23: Reloading
[INFO 17:54:18.024518] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/build/tootle/parts/tootle/build/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
````

#### Additional info (if needed):
This appears to be the error:

ERROR:/build/tootle/parts/tootle/build/src/API/NotificationType.vala:43:**tootle_notification_type_from_string: code should not be reached**

**Comment by bleakgrey** [comment] 2021-03-03 23:04
Dupe of #252 and many, many more

**Closed by bleakgrey** 2021-03-03 23:04 UTC
Labels: bug

**Comment by sgtnasty** [comment] 2021-03-03 23:09
After looking at the code I realized that the snap version must be older. because the source on git clears this issue up better. Sorry about that, I tried to search but it did not come up.

**Comment by bleakgrey** [comment] 2021-03-03 23:11
It's okay, hope that 1.0 works for you nicely 👍🏻
