### ISSUE TITLE
Add "Clear all notifications" button

### ISSUE THREAD

**Issue by BaptisteGelez** [bleakgrey/tootle#5] opened 2018-05-15 08:20 UTC
It would be nice to have the same behavior as the Wingpanel indicator for notifications: only show a bell when there is no unread notifications, and the bell with a red dot when we have received a new one.

**Comment by bleakgrey** [comment] 2018-05-15 09:49
It should already do that if you have dismissed all of the notifications :/

**Comment by bleakgrey** [comment] 2018-05-15 10:03
I just checked that and it works as expected, although it loads old notifications on start and displays them as new.

I'll add a new "Clear all" button or something something to fix that.

**Comment by bleakgrey** [comment] 2018-10-27 09:08
Dupe of #81

**Closed by bleakgrey** 2018-10-27 09:08 UTC
Labels: idea
