### ISSUE TITLE
Crash with FLOSS.social in a pop_os VM

### ISSUE THREAD

**Issue by Exalm** [bleakgrey/tootle#150] opened 2019-05-28 21:43 UTC
```
exalm@pop-os:~$ G_MESSAGES_DEBUG=all flatpak run com.github.bleakgrey.tootle 
(flatpak:25124): GLib-GIO-DEBUG: 02:41:42.192: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(flatpak run:25124): flatpak-DEBUG: 02:41:42.198: No installations directory in /etc/flatpak/installations.d. Skipping
(flatpak run:25124): flatpak-DEBUG: 02:41:42.198: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.198: Opening user flatpak installation at path /home/exalm/.local/share/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.198: Opening user flatpak installation at path /home/exalm/.local/share/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.198: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.199: Opening user flatpak installation at path /home/exalm/.local/share/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.199: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:25124): flatpak-DEBUG: 02:41:42.230: Cleaning up unused container id 3178615632
(flatpak run:25124): flatpak-DEBUG: 02:41:42.230: Allocated instance id 1430997532
(flatpak run:25124): flatpak-DEBUG: 02:41:42.230: Add defaults in dir /com/github/bleakgrey/tootle/
(flatpak run:25124): flatpak-DEBUG: 02:41:42.230: Add locks in dir /com/github/bleakgrey/tootle/
(flatpak run:25124): flatpak-DEBUG: 02:41:42.248: Allowing wayland access
(flatpak run:25124): flatpak-DEBUG: 02:41:42.248: Allowing x11 access
(flatpak run:25124): flatpak2-DEBUG: 02:41:42.253: bwrap --args 34 = --ro-bind /srv /srv --ro-bind /media /media --bind /run /run --ro-bind /usr /usr --ro-bind '/lost+found' '/lost+found' --ro-bind /opt /opt --symlink boot/initrd.img-5.0.0-13-generic /initrd.img.old --ro-bind /home /home --symlink usr/lib64 /lib64 --symlink usr/lib /lib --ro-bind /boot /boot --bind /tmp /tmp --symlink boot/initrd.img-5.0.0-15-generic /initrd.img --symlink usr/bin /bin --ro-bind /etc /etc --symlink usr/libx32 /libx32 --symlink boot/vmlinuz-5.0.0-15-generic /vmlinuz --ro-bind /root /root --symlink usr/sbin /sbin --bind /var /var --ro-bind /proc /proc --ro-bind /dev /dev --ro-bind /sys /sys --symlink usr/lib32 /lib32 --ro-bind /mnt /mnt --symlink boot/vmlinuz-5.0.0-13-generic /vmlinuz.old --bind /run/user/1000/.dbus-proxy/ /run/user/1000/.dbus-proxy/ --file 32 /.flatpak-info
(flatpak run:25124): flatpak2-DEBUG: 02:41:42.253: bwrap --args 36 = --fd=35 unix:path=/run/user/1000/bus /run/user/1000/.dbus-proxy/session-bus-proxy-I3RJ2Z --filter '--own=com.github.bleakgrey.tootle.*' '--own=org.mpris.MediaPlayer2.com.github.bleakgrey.tootle.*' --talk=ca.desrt.dconf '--call=org.freedesktop.portal.*=*' '--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*' 'unix:abstract=/tmp/dbus-Tb8jDT1n5M,guid=59e77525674013f184a7d81e5cedaad2' /run/user/1000/.dbus-proxy/a11y-bus-proxy-L6SJ2Z --filter --sloppy-names --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller
(flatpak run:25124): flatpak-DEBUG: 02:41:42.253: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
(flatpak run:25124): GLib-DEBUG: 02:41:42.254: posix_spawn avoided (automatic reaping requested) (fd close requested) (child_setup specified) 
(flatpak run:25124): flatpak2-DEBUG: 02:41:42.263: bwrap --args 34 = --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files /usr --lock-file /usr/.ref --ro-bind /var/lib/flatpak/app/com.github.bleakgrey.tootle/x86_64/stable/f5eb5e51f442d29edbd504f381630221da424149962430f536ea03ae6466b8ae/files /app --lock-file /app/.ref --ro-bind /var/lib/flatpak/runtime/com.github.bleakgrey.tootle.Locale/x86_64/stable/c69838b88cdb8e450e151ca5a93aa20535b58b03801ee6fd7f905ab5becefdee-en/files /app/share/runtime/locale --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08/631068e1e615c5587c04079e220654431496ed5eb3b37dcce6eb4a05cbd1b6f8/files /usr/lib/x86_64-linux-gnu/ffmpeg --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.Locale/x86_64/18.08/2bdbceb75465fa881b403a73df81c72fb10453c711c4d7075f2cc39991ee3f90-en/files /usr/share/runtime/locale --tmpfs /usr/share/runtime/share/themes --ro-bind /var/lib/flatpak/runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22/6154d9636034f0866dc7a2a08815931c641298ccfe1f5dd180875f4a4cb20f03/files /usr/share/runtime/share/themes/Pop/gtk-3.0 --ro-bind-data 18 /run/flatpak/ld.so.conf.d/runtime-001-org.freedesktop.Platform.html5-codecs.conf --proc /proc --unshare-pid --dir /tmp --dir /var/tmp --dir /run/host --dir /run/user/1000 --setenv XDG_RUNTIME_DIR /run/user/1000 --symlink ../run /var/run --ro-bind /sys/block /sys/block --ro-bind /sys/bus /sys/bus --ro-bind /sys/class /sys/class --ro-bind /sys/dev /sys/dev --ro-bind /sys/devices /sys/devices --symlink /etc/timezone /var/db/zoneinfo --ro-bind-data 20 /etc/passwd --ro-bind-data 21 /etc/group --ro-bind-data 22 /etc/pkcs11/pkcs11.conf --ro-bind /etc/machine-id /etc/machine-id --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/pulse /etc/pulse --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/ssl /etc/ssl --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/geoclue /etc/geoclue --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/issue.net /etc/issue.net --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/security /etc/security --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/profile.d /etc/profile.d --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/vdpau_wrapper.cfg /etc/vdpau_wrapper.cfg --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/fonts /etc/fonts --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/gtk-3.0 /etc/gtk-3.0 --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/rpc /etc/rpc --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/mke2fs.conf /etc/mke2fs.conf --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/services /etc/services --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/xattr.conf /etc/xattr.conf --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/ca-certificates.conf /etc/ca-certificates.conf --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/environment /etc/environment --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/ld.so.conf /etc/ld.so.conf --symlink ../../proc/self/mounts /etc/mtab --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/bindresvport.blacklist /etc/bindresvport.blacklist --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/issue /etc/issue --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/xdg /etc/xdg --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/netconfig /etc/netconfig --symlink ../usr/lib/os-release /etc/os-release --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/alsa /etc/alsa --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/nsswitch.conf /etc/nsswitch.conf --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/protocols /etc/protocols --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/732d970491956e1c5b034a35cd24e7146c80bbca5e665fffa74ec7d66d5f505c/files/etc/dbus-1 /etc/dbus-1 --bind /home/exalm/.var/app/com.github.bleakgrey.tootle/cache /var/cache --bind /home/exalm/.var/app/com.github.bleakgrey.tootle/data /var/data --bind /home/exalm/.var/app/com.github.bleakgrey.tootle/config /var/config --bind /home/exalm/.var/app/com.github.bleakgrey.tootle/cache/tmp /var/tmp --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/bin /bin --symlink usr/sbin /sbin --seccomp 23 --ro-bind /run/user/1000/.flatpak-helper/monitor /run/host/monitor --symlink /run/host/monitor/localtime /etc/localtime --symlink /run/host/monitor/resolv.conf /etc/resolv.conf --symlink /run/host/monitor/host.conf /etc/host.conf --symlink /run/host/monitor/hosts /etc/hosts --symlink /run/host/monitor/timezone /etc/timezone --ro-bind-data 24 /etc/pkcs11/modules/p11-kit-trust.module --ro-bind /run/user/1000/.flatpak-helper/pkcs11-flatpak-25128 /run/user/1000/p11-kit/pkcs11 --ro-bind-data 25 /etc/ld.so.conf --ro-bind-data 19 /etc/ld.so.cache --ro-bind /run/user/1000/.flatpak/1430997532 /run/user/1000/.flatpak/1430997532 --lock-file /run/user/1000/.flatpak/1430997532/.ref --file 27 /.flatpak-info --ro-bind-data 28 /.flatpak-info --symlink ../../../.flatpak-info /run/user/1000/flatpak-info --info-fd 29 --bind /run/user/1000/doc/by-app/com.github.bleakgrey.tootle /run/user/1000/doc --dev /dev --bind /run/user/1000/app/com.github.bleakgrey.tootle /run/user/1000/app/com.github.bleakgrey.tootle --dir /home/exalm --ro-bind /home/exalm/.config/dconf /home/exalm/.config/dconf --dir /home/exalm/.local/share/flatpak --dir /home/exalm/.var/app --bind /home/exalm/.var/app/com.github.bleakgrey.tootle /home/exalm/.var/app/com.github.bleakgrey.tootle --bind /run/user/1000/dconf /run/user/1000/dconf --tmpfs /tmp/.X11-unix --ro-bind /tmp/.X11-unix/X1 /tmp/.X11-unix/X99 --ro-bind-data 31 /run/user/1000/Xauthority --ro-bind /run/user/1000/.dbus-proxy/session-bus-proxy-I3RJ2Z /run/user/1000/bus --ro-bind /run/user/1000/.dbus-proxy/a11y-bus-proxy-L6SJ2Z /run/user/1000/at-spi-bus --sync-fd 33 --bind /run/systemd/journal/socket /run/systemd/journal/socket --bind /run/systemd/journal/stdout /run/systemd/journal/stdout --ro-bind /usr/share/fonts /run/host/fonts --ro-bind /var/cache/fontconfig /run/host/fonts-cache --ro-bind /home/exalm/.cache/fontconfig /run/host/user-fonts-cache --ro-bind-data 32 /run/host/font-dirs.xml --ro-bind /usr/share/icons /run/host/share/icons --symlink /app/lib/debug/source /run/build --symlink /usr/lib/debug/source /run/build-runtime
(flatpak run:25124): flatpak-DEBUG: 02:41:42.263: Running 'bwrap --args 34 com.github.bleakgrey.tootle'
Gtk-Message: 02:41:42.348: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:41:42.348: Failed to load module "canberra-gtk-module"
[INFO 02:41:42.349226] Application.vala:155: Tootle version: 0.2.0
[INFO 02:41:42.349282] Application.vala:157: Kernel version: 5.0.0-15-generic
(com.github.bleakgrey.tootle:2): dconf-DEBUG: 02:41:42.486: watch_fast: "/com/github/bleakgrey/tootle/" (establishing: 0, active: 0)
(com.github.bleakgrey.tootle:2): dconf-DEBUG: 02:41:42.487: watch_established: "/com/github/bleakgrey/tootle/" (establishing: 1)
[INFO 02:41:42.621976] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 02:41:42.641868] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 02:41:42.645425] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 02:41:42.646895] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:2): Gtk-WARNING **: 02:41:42.713: gtk_window_set_titlebar() called on a realized window
[INFO 02:41:43.564568] Watchlist.vala:23: Reloading
[INFO 02:41:43.564615] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/run/build/tootle/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
exalm@pop-os:~$ 
```

**Comment by Exalm** [comment] 2019-05-28 22:26
Just in case: crashes just the same on Fedora 30 (flatpak from flathub too). I am able to authenticate, it shows up the feed for about a second, then crashes.

**Comment by bleakgrey** [comment] 2019-05-29 12:14
Dupe of #140

**Closed by bleakgrey** 2019-05-29 12:14 UTC

**Comment by dermitdemdino** [comment] 2019-07-14 04:13
Me too. Tootle crashes during startup.

[INFO 06:11:29.357323] Application.vala:155: Tootle version: 0.2.0
[INFO 06:11:29.357368] Application.vala:157: Kernel version: 4.15.0-54-generic

ERROR:/run/build/tootle/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
