### ISSUE TITLE
Crash on start on Home Timeline from a HTML parsing issue

### ISSUE THREAD

**Issue by CaseOf** [bleakgrey/tootle#141] opened 2019-04-20 17:57 UTC
Hi,
Tootle is crashing on startup because it can’t parse HTML with some characters not escaped:
```
quentin@gentoo_quentin ~ $ com.github.bleakgrey.tootle 
[INFO 19:53:58.688223] Application.vala:154: Tootle version: 0.2.0
[INFO 19:53:58.688257] Application.vala:156: Kernel version: 4.19.27-gentoo-r1
[INFO 19:53:58.739274] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 19:53:58.741070] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 19:53:58.743439] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 19:53:58.744439] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:3663): Gtk-WARNING **: 19:53:58.800: gtk_window_set_titlebar() called on a realized window
[INFO 19:53:59.126534] Watchlist.vala:23: Reloading
[INFO 19:53:59.126569] Watchlist.vala:34: Watching for 0 users and 0 hashtags

(com.github.bleakgrey.tootle:3663): Gtk-WARNING **: 19:53:59.441: Failed to set text '<a href="https://mamot.fr/@jz"><b>J?r?mie Zimmermann ? ? ? <3</b></a> boosted' from markup due to error parsing markup: Error on line 1 char 82: ?3<? is not a valid name

(com.github.bleakgrey.tootle:3663): Gtk-WARNING **: 19:53:59.441: Failed to set text '<a href="https://mamot.fr/@jz"><b>J?r?mie Zimmermann ? ? ? <3</b></a> boosted' from markup due to error parsing markup: Error on line 1 char 82: ?3<? is not a valid name
**
ERROR:/var/tmp/portage/net-im/tootle-0.2.0/work/tootle-0.2.0/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted
```

**Comment by bleakgrey** [comment] 2019-04-21 14:29
No, HTML escaping isn't the issue in this case.

**Comment by bleakgrey** [comment] 2019-04-21 14:29
What instance are you using?

**Comment by CaseOf** [comment] 2019-04-21 15:07
framapiaf.org

**Comment by bleakgrey** [comment] 2019-04-24 18:52
Dupe of #140

**Closed by bleakgrey** 2019-04-24 18:52 UTC
