### ISSUE TITLE
Core Dump on Ubuntu's Universe Repo Version 0.2.0-2ubuntu1

### ISSUE THREAD

**Issue by marathone** [bleakgrey/tootle#252] opened 2020-10-16 12:50 UTC
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
__  Shouldn't Core Dump

#### What happened instead:
__
It Core Dumped.

#### How to reproduce:
1. __
2. __

#### Screenshots (if applicable):
__

#### Build context:
 - **Distro:** __
 - **App version:** __
 - **Build type:** Flatpak / Built from source / Built by a third-party maintainer

#### Logs:
*(Terminal logs are often invaluable. If you can, launch the app from terminal with `com.github.bleakgrey.tootle` and paste the output here)*

(tootle:10432): Gtk-WARNING **: 08:41:51.839: Failed to set text 'Экипаж МКС сумел обнаружить место утечки воздуха с&nbsp;борта космической станции. Для&nbsp;решения проблемы задействовали чайный пакетик и&nbsp;скотч.
<a href="https://phreedom.tk/tags/%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F"   >#<span>станция</span></a> <a href="https://phreedom.tk/tags/%D0%BA%D0%BE%D1%81%D0%BC%D0%BE%D1%81"   >#<span>космос</span></a> <a href="https://phreedom.tk/tags/%D1%83%D1%82%D0%B5%D1%87%D0%BA%D0%B0"   >#<span>утечка</span></a>
<a href="https://ria.ru/20201015/mks-1579907564.html"  ><span >https://</span><span >ria.ru/20201015/mks-1579907564</span><span >.html</span></a>' from markup due to error parsing markup: Error on line 1: Entity name “nbsp” is not known

(tootle:10432): Gtk-WARNING **: 08:41:51.839: Failed to set text 'Экипаж МКС сумел обнаружить место утечки воздуха с&nbsp;борта космической станции. Для&nbsp;решения проблемы задействовали чайный пакетик и&nbsp;скотч.
<a href="https://phreedom.tk/tags/%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F"   >#<span>станция</span></a> <a href="https://phreedom.tk/tags/%D0%BA%D0%BE%D1%81%D0%BC%D0%BE%D1%81"   >#<span>космос</span></a> <a href="https://phreedom.tk/tags/%D1%83%D1%82%D0%B5%D1%87%D0%BA%D0%B0"   >#<span>утечка</span></a>
<a href="https://ria.ru/20201015/mks-1579907564.html"  ><span >https://</span><span >ria.ru/20201015/mks-1579907564</span><span >.html</span></a>' from markup due to error parsing markup: Error on line 1: Entity name “nbsp” is not known
**
ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Bail out! ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)

#### Additional info (if needed):
__

**Comment by bleakgrey** [comment] 2020-10-16 12:59
Tootle 0.2 was first released in 2018 and is no longer supported. I'm pretty sure Ubuntu's repos will be updated once I ship 1.0.

For now, you can grab 1.0-alpha1 from Flathub right now, or build and install it from source. Despite it being an alpha, it should be stable enough to be your daily driver.

**Closed by bleakgrey** 2020-10-16 12:59 UTC
Labels: bug

**Comment by murtezayesil** [comment] 2021-02-10 06:51
__What should happen:__

Shouldn't Core Dump

__What happened instead:__

Core dumped and crashed

__How to reproduce:__

- Receive "FOLLOW" notification.
    - If follow happened while offline then app will attempt to generate a "FOLLOW" notification causing it to crash 1 or 2 seconds after launch.

__Build context:__

__Distro:__ Elementary OS 5.1.7
__Version:__ 0.2.0
__Kernel version:__ 5.4.0-65-generic
__Build Type:__ Elementary OS AppCenter. So, I guess official 

__Logs:__
```
$ com.github.bleakgrey.tootle 
[INFO 11:41:52.697925] Application.vala:156: Tootle version: 0.2.0
[INFO 11:41:52.698018] Application.vala:158: Kernel version: 5.4.0-65-generic
[INFO 11:41:52.794635] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 11:41:52.800731] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 11:41:52.809002] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 11:41:52.812401] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 11:41:54.244876] Watchlist.vala:23: Reloading
[INFO 11:41:54.244969] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/build/com.github.bleakgrey.tootle-0.2.0/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
```

__Additional info:__

According to logs, crash happens when this code is reached: https://github.com/bleakgrey/tootle/blob/0e655023495b1a438dadb65da476688d2583a7d4/src/API/NotificationType.vala#L43

Crash can be avoided if there is no "FOLLOW" notification. I had to Notifications are cleaned (marked read and deleted) using another client or web interface. Since "FOLLOW" notification is deleted, Tootle app doesn't attempt to generate a follow notification thus not crash.

I tooted to be followed after disabling notifications for Tootle in System Settings and I hoped that would help. I received follow notifications as expected without a crash but app froze when I tried to close it. It was constantly sending `[FATAL 12:32:18.827204] [Gtk] gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed` error messages on terminal. I had to kill the app.
Here is the toot I sent: https://fosstodon.org/@murtezayesil/105705481422143139
