### ISSUE TITLE
Crash when i launch tootle

### ISSUE THREAD

**Issue by pirboazo** [bleakgrey/tootle#154] opened 2019-06-13 14:57 UTC
Hi
After append a new account
it's impossible to change.

and now the Tootle crash at startup.

**Comment by demolg** [comment] 2019-06-23 01:55
Me, too.
ERROR:../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached

**Comment by jolupa** [comment] 2019-07-23 15:14
Hi!
Same problem here. I build the package for CRUX and I can't open the application after adding my account.
Any hint?

**Comment by ldutra** [comment] 2019-08-16 19:38
Same here.  Worked with one account, now with two it crashes under Debian (testing/unstable):

`tootle &
[2] 24489
l@nuc:~$ 
(tootle:24489): dbind-WARNING **: 16:34:41.362: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[INFO 16:34:41.392872] Application.vala:155: Tootle version: 0.2.0
[INFO 16:34:41.392937] Application.vala:157: Kernel version: 5.0.0-trunk-amd64
[INFO 16:34:41.433233] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 16:34:41.433383] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 16:34:41.435666] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 16:34:41.439787] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 16:34:41.442778] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 16:34:48.449712] Watchlist.vala:23: Reloading
[INFO 16:34:48.449766] Watchlist.vala:34: Watching for 0 users and 0 hashtags
[ERROR 16:34:49.034950] [GLib-GIO] Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed

[2]+  Trappe pour point d'arrêt et de trace              tootle
l@nuc:~$ ``

**Comment by mattdementous** [comment] 2019-08-25 21:06
I am having the same issue as Idutra, with the io.elementary.desktop.wingpanel.datetime is not installed issue, except I'm on Pop_OS.
App launches, timeline tries to load and then crashes.

**Comment by chpio** [comment] 2019-08-30 09:31
other error, but still a "crash on startup"
```
$ flatpak run com.github.bleakgrey.tootle
Gtk-Message: 11:28:23.396: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:28:23.396: Failed to load module "canberra-gtk-module"
[INFO 11:28:23.397008] Application.vala:155: Tootle version: 0.2.0
[INFO 11:28:23.397033] Application.vala:157: Kernel version: 5.1.21-050121-generic
[INFO 11:28:23.452068] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 11:28:23.467889] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 11:28:23.471274] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 11:28:23.472726] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:2): Gtk-WARNING **: 11:28:23.535: gtk_window_set_titlebar() called on a realized window
[INFO 11:28:23.910794] Watchlist.vala:23: Reloading
[INFO 11:28:23.910855] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/run/build/tootle/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
```

**Comment by bleakgrey** [comment] 2019-09-07 19:40
Dupe of #140

**Closed by bleakgrey** 2019-09-07 19:40 UTC
