### ISSUE TITLE
v0.2.0 from flatpak crashes while loading home TL

### ISSUE THREAD

**Issue by asgartech** [bleakgrey/tootle#140] opened 2019-04-13 20:45 UTC
Running the app from the terminal yields the following result.

demifiend@imaginos:~
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.bleakgrey.tootle com.github.bleakgrey.tootle
Gtk-Message: 16:44:05.948: Failed to load module "canberra-gtk-module"
[INFO 16:44:05.963236] Application.vala:155: Tootle version: 0.2.0
[INFO 16:44:05.963306] Application.vala:157: Kernel version: 4.19.0-1-amd64
[INFO 16:44:06.150859] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 16:44:06.188197] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 16:44:06.194635] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 16:44:06.197580] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:3): Gtk-WARNING **: 16:44:06.355: gtk_window_set_titlebar() called on a realized window
[INFO 16:44:07.271388] Watchlist.vala:23: Reloading
[INFO 16:44:07.271668] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/run/build/tootle/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached

**Comment by bleakgrey** [comment] 2019-04-13 21:16
What instance are you using? It looks like Tootle found an unsupported notification type.

**Comment by asgartech** [comment] 2019-04-14 02:41
mastodon.sdf.org

**Comment by bleakgrey** [comment] 2019-04-24 19:00
I'm kind of regretting that I'm just crashing Tootle without printing that mysterious 5th notification type in the logs. Looks like it's got quite popular.

**Comment by bleakgrey** [comment] 2019-04-24 19:03
Did your home timeline contain a poll or anything _new_ by any chance? I'm failing to understand what's going wrong.

**Comment by asgartech** [comment] 2019-04-25 01:12
On Wed, Apr 24, 2019, at 3:03 PM, Bleak Grey wrote:
> Did your home timeline contain a poll or anything *new* by any chance? 
> I'm failing to understand what's going wrong.

There might have been a poll. I don't recall because it's been a few days. Sorry.

-- 
Matthew Graybosch
https://www.matthewgraybosch.com
"Out of order? Even in the future nothing works."

**Comment by cleac** [comment] 2019-04-30 05:41
In fact, it was a poll. I've experienced very same issue and the only thing that has changed was polls in my notifications

**Comment by cleac** [comment] 2019-04-30 06:01
I think I can add a fallback to prevent application from crashing when we get new notifications 😉️

**Comment by cleac** [comment] 2019-04-30 06:11
@bleakgrey can you please look at the PR #143? This should cover cases when application gets notifications of type it does not know anything about

**Comment by alien2003** [comment] 2019-05-15 08:34
There is also a problem with lor.sh

**Comment by keponk** [comment] 2019-05-27 22:37
+1 on this. hope it can get fixed soon. Tootle is my go-to mastodon app

**Comment by nielsk** [comment] 2019-06-04 07:21
I am on fedora 30. Installed it, started it, logged in, crash. Started it again, crash etc.
```
[INFO 09:19:12.676914] Application.vala:155: Tootle version: 0.2.0
[INFO 09:19:12.676966] Application.vala:157: Kernel version: 5.1.5-300.fc30.x86_64
[INFO 09:19:12.924368] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 09:19:12.989068] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 09:19:12.999938] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 09:19:13.008055] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 09:19:14.561241] Watchlist.vala:23: Reloading
[INFO 09:19:14.561296] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/run/build/tootle/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached

**Comment by cleac** [comment] 2019-06-04 07:24
@nielsk The issue is the same: application has got a notification type it can't handle. 

@bleakgrey what about merging the fix I've proposed? It *will* fix issue completely in fact :wink:

**Comment by yannicka** [comment] 2019-10-15 20:24
I've compiled from master just now, and I've the same problem about "poll" (crash on startup):

```text
ERROR:../src/API/NotificationType.vala:48:tootle_api_notification_type_from_string: code should not be reached
```

The value of `str` is `"poll"`, which is not catched:

https://github.com/bleakgrey/tootle/blob/d8fc951fb0c0c0f85a3869c6abfc79b2c3d83215/src/API/NotificationType.vala#L31-L50

**Comment by absort0** [comment] 2019-10-16 18:15
Just compiled from master and having the same issue too. I'm running Tootle on a Debian 10 machine with i3wm and my instance is **freeradical.zone**. The only poll I have on my notifications is from a month ago, but yeah, not many notifications things going on since then :nerd_face:

**Comment by cesasol** [comment] 2019-10-17 18:24
Just another user with the same crash using Arch and mastodon.social

**Comment by seekr** [comment] 2019-10-21 01:45
Yet another user with same error `ERROR:/build/com.github.bleakgrey.tootle-0.2.0/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached` but I'm on Elementary

**Comment by vbatts** [comment] 2019-11-10 15:47
> What instance are you using? It looks like Tootle found an unsupported notification type.

I'm hitting this now, using the tootle packaged in via flathub.
`Tootle  com.github.bleakgrey.tootle     0.2.0   stable  user`
Tootle is configured for mastodon.social and fosstodon.org

**Comment by taciturasa** [comment] 2019-12-20 03:30
Here with the same error from the appcenter on elementary. Nothing different in my log.

**Comment by NIXOYE** [comment] 2020-02-25 18:12
@cleac would you be willing to create a fork with your fix? The dev doesn't seem to be active and I'm having the same issue

**Comment by cleac** [comment] 2020-02-25 18:44
@taciturasa @NIXOYE for now, some of my fixes are already in a separate branch of my fork and can be reviewed [here](https://github.com/cleac/tootle/tree/with-fixes). TBH I am not sure I will be able to support the forked version on my own (not too much experience in Vala, GTK and supporting desktop applications in Linux ecosystem). Though, if someone will help me with support, I can participate.

For now, I suggest moving this discussion to different medium because I consider discussing the probable fork creation in original repository as unethical. I propose moving this discussion to [an issue in my fork](https://github.com/cleac/tootle/issues/1)

**Comment by bleakgrey** [comment] 2020-06-20 10:29
Fixed in master

**Closed by bleakgrey** 2020-06-20 10:29 UTC
Labels: bug
