### ISSUE TITLE
Some icons on non-eOS systems are missing

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#20] opened 2018-05-26 13:25 UTC

**Comment by johannesgunnar** [comment] 2018-08-12 20:12
Can confirm that this is the case on Ubuntu 18.04, using latest version of Tootle from flathub.

![mynd](https://user-images.githubusercontent.com/2924543/44005990-ec354cca-9e6b-11e8-89a6-39e1d6a27c8d.png)

**Comment by alcinnz** [comment] 2018-08-14 09:43
Here's a list of icons you should expect to be available on all desktops: https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html . I think you'll find it handy.

**Comment by vinzv** [comment] 2018-08-14 19:52
Same here on openSUSE Leap 15:

![animation](https://user-images.githubusercontent.com/74432/44114718-4d89b6c2-a00c-11e8-9f1a-68bf29b68105.gif)

**Comment by brortao** [comment] 2018-08-30 15:52
On the latest Fedora, the "following" icon is missing: 

![screenshot from 2018-08-30 17-49-35](https://user-images.githubusercontent.com/1309951/44863410-5adb2180-ac7d-11e8-86b2-fa11e7c1c725.png)

Also, the favorites icon is a little "i" - don't know if that's intentional.
![screenshot from 2018-08-30 17-50-01](https://user-images.githubusercontent.com/1309951/44863433-67f81080-ac7d-11e8-8cee-4f047fa8f837.png)

**Comment by fschaap** [comment] 2018-08-31 08:16
I can confirm the issue with Tootle installed from the AUR on Manjaro (Cinnamon DE). Missing are:
- the notifications icon
- the reply button icon
- the following icon

**Comment by fschaap** [comment] 2018-08-31 14:54
Oh, and I can confirm @johannesgunnar's observation that the right icons will briefly show before disappearing. When I start Tootle without any registered users, the Notifications icon for instance shows correctly. The moment I have authorized a user, the notifications icon disappears.

**Comment by cagatay-y** [comment] 2018-09-02 12:11
Notification icon is fixed in master.
> Also, the favorites icon is a little "i" - don't know if that's intentional.

There is issue #29 to replace it with an icon that will look correct across different themes. Looks like it will be fixed in the next version.

**Comment by toitoinebzh** [comment] 2018-12-16 22:38
same issue here on xubuntu 18.04

![image](https://user-images.githubusercontent.com/44553182/50059789-a44b7000-018b-11e9-892d-8c161b8168a5.png)

**Comment by PoorPocketsMcNewHold** [comment] 2019-05-11 08:43
> On the latest Fedora, the "following" icon is missing:
> 
> ![screenshot from 2018-08-30 17-49-35](https://user-images.githubusercontent.com/1309951/44863410-5adb2180-ac7d-11e8-86b2-fa11e7c1c725.png)
> 
> Also, the favorites icon is a little "i" - don't know if that's intentional.
> ![screenshot from 2018-08-30 17-50-01](https://user-images.githubusercontent.com/1309951/44863433-67f81080-ac7d-11e8-8cee-4f047fa8f837.png)

Interesting thing, I do have this same issue... On Elementary OS. 
![image](https://user-images.githubusercontent.com/13170204/57567446-9a940480-73d9-11e9-829a-b3893c222367.png)

**Closed** 2020-07-30 22:09 UTC
Labels: compatibility, design needed
