### ISSUE TITLE
Crash shortly after startup

### ISSUE THREAD

**Issue by select** [bleakgrey/tootle#267] opened 2020-12-09 10:52 UTC
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
Should run without crashing

#### What happened instead:
Crash about 1s after the startup

#### How to reproduce:
Start the application

#### Screenshots (if applicable):
__

#### Build context:
 - **Distro:** Ubuntu 20.10
 - **App version:** [INFO 11:51:21.370652] Application.vala:156: Tootle version: 0.2.0
[INFO 11:51:21.370674] Application.vala:158: Kernel version: 5.8.0-31-generic

 - **Build type:** installed with `apt install tootle`

#### Logs:
```
ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Bail out! ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
[1]    23042 abort (core dumped)  tootle
```

**Comment by bleakgrey** [comment] 2020-12-09 10:53
Dupe of #252

**Closed by bleakgrey** 2020-12-09 10:53 UTC
Labels: bug
