### ISSUE TITLE
[bug] Sometimes reply to reply is posted twice

### ISSUE THREAD

**Issue by cleac** [bleakgrey/tootle#127] opened 2019-02-01 09:09 UTC
Sometimes, when I reply to a reply to my toot, it gets composed twice and I have to remove duplicate.

Using version `0.2.0` from flatpak with mastodon.technology instance.

Steps to reproduce:
1. Create a toot
2. Wait untill someone replies you
3. Reply him (can be with long posts only)
4. Look at the timeline: there should be two identical toots. 

---

I could look at this, but I'm a but I am not that great with Vala and Gtk and have a bit tight schedule. It feels pretty imperative to me and if nobody will take this in a week, I will try to resolve issue by myself and will make a PR :)

**Comment by bleakgrey** [comment] 2020-07-30 15:10
Can't reproduce on `master`. Guess it's fixed now ¯\_(ツ)_/¯

**Closed by bleakgrey** 2020-07-30 15:10 UTC
